#!/usr/bin/env sh
# Copyright 2017 LasLabs Inc.
# License Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0.html).

set -e

sleep 10

curl --fail http://localhost:8080

echo "Curl passed on $DOCKER_CONTAINER_ID"
